<?php

namespace Dwarse\AuthBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AuthTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthTokenRepository extends EntityRepository {
}
