AuthBundle\Entity\User:
    exclusion_policy: none
    properties:
        id:
            groups: ['user']
        login:
            groups: ['user']
        email:
            groups: ['user']
        role:
            groups: ['user']
        confirmed:
            groups: ['user']
        confirmationToken:
            groups: ['user']
        authToken:
            groups: ['user']