AuthBundle\Entity\AuthToken:
    exclusion_policy: none
    properties:
        id:
            groups: ['user', 'employeur']
        value:
            groups: ['user', 'employeur']
        createdAt:
            groups: ['user', 'employeur']