AuthBundle\Entity\User:
    exclusion_policy: none
    properties:
        id:
            groups: ['user', 'employeur']
        login:
            groups: ['user', 'employeur']
        email:
            groups: ['user', 'employeur']
        role:
            groups: ['user', 'employeur']
        confirmed:
            groups: ['user', 'employeur']
        confirmationToken:
            groups: ['user', 'employeur']
        authToken:
            groups: ['user', 'employeur']