AuthBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: login
    properties:
        login:
            - NotBlank:
                message: 'Le champs login ne doit pas être vide'
            - Type:
                type: string
                message: 'Veuillez entrer un login correct'
        email:
            - NotBlank:
                message: 'Le champs email ne doit pas être vide'
            - Email:
                message: 'Veuillez entrer un email correct'
        role:
            - NotBlank:
                message: 'Le champs role ne doit pas être vide'
            - Choice:
                choices: [ROLE_EMPLOYEUR, ROLE_COMMERCANT]
                message: 'Veuillez entrer un role correct'
                strict: true
        plainPassword:
            - NotBlank:
                groups: [New, FullUpdate]
                message: 'Le champs mot de passe ne doit pas être vide'
            - Type:
                type: string
                message: 'Veuillez entrer un mot de passe correct'
            - Length:
                min: 5
                max: 25

AuthBundle\Entity\Credentials:
    properties:
        login:
            - NotBlank:
                message: Le champs login ne doit pas être vide
            - Type:
                type: string
                message: Veuillez entrer un login correct
        password:
            - NotBlank:
                message: Le champs login ne doit pas être vide
            - Type:
                type: string
                message: Veuillez entrer un mot de passe correct
            - Length:
                min: 5
                max: 25
