parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: dwarse
    database_password: null
    database_driver: pdo_sqlite
    database_user: test
    database_path: "%kernel.root_dir%/sqlite.db.cache"
    database_memory: true
    database_charset: utf8
