parameters:
    database_url: mysql://b08d18194dd976:a94fd896@eu-cdbr-west-01.cleardb.com/heroku_9214b9902249f51?reconnect=true
#    database_host: eu-cdbr-west-01.cleardb.com
#    database_port: null
#    database_name: heroku_9214b9902249f51
#    database_user: b08d18194dd976:a94fd896
#    database_password: null