insc:
    type:     rest
    resource: AuthBundle\Controller\UserController
    prefix:   /auth

auth:
    type:     rest
    resource: AuthBundle\Controller\AuthTokenController
    prefix:   /auth

images:
    type:     annotation
    resource: AuthBundle\Controller\ImageController
    prefix:   /image
