insc:
    type:     rest
    resource: AuthBundle\Controller\UserController
    prefix:   /auth

login:
    type:     rest
    resource: AuthBundle\Controller\LoginController
    prefix:   /auth

auth:
    type:     rest
    resource: AuthBundle\Controller\AuthTokenController
    prefix:   /auth

employeurProfile:
    type:     rest
    resource: EmployeurBundle\Controller\ProfileController
    prefix:   /employeur

employeurEmploye:
    type:     rest
    resource: EmployeurBundle\Controller\EmployeController
    prefix:   /employeur

commercantProfile:
    type:     rest
    resource: CommercantBundle\Controller\ProfileController
    prefix:   /commercant

employeProfile:
    type:     rest
    resource: EmployeBundle\Controller\ProfileController
    prefix:   /employe