insc:
    type:     rest
    resource: AuthBundle\Controller\UserController
    prefix:   /auth

login:
    type:     rest
    resource: AuthBundle\Controller\LoginController
    prefix:   /auth

images:
    type:     annotation
    resource: AuthBundle\Controller\ImageController
    prefix:   /image

auth:
    type:     rest
    resource: AuthBundle\Controller\AuthTokenController
    prefix:   /auth

employeProfile:
    type:     rest
    resource: EmployeurBundle\Controller\ProfileController
    prefix:   /employeur