insc:
    type:     rest
    resource: AuthBundle\Controller\UserController
    prefix:   /auth

login:
    type:     rest
    resource: AuthBundle\Controller\LoginController
    prefix:   /auth

auth:
    type:     rest
    resource: AuthBundle\Controller\AuthTokenController
    prefix:   /auth

employeurEmploye:
    type:     rest
    resource: EmployeurBundle\Controller\EmployeController
    prefix:   /employeur

employeurProfile:
    type:     rest
    resource: EmployeurBundle\Controller\ProfileController
    prefix:   /employeur

employeurOpposition:
    type:     rest
    resource: EmployeurBundle\Controller\OppositionController
    prefix:   /employeur

commercantProfile:
    type:     rest
    resource: CommercantBundle\Controller\ProfileController
    prefix:   /commercant

commercantConsultation:
    type:     rest
    resource: CommercantBundle\Controller\ConsultationController
    prefix:   /commercant/consultation

commercantPaiement:
    type:     rest
    resource: TransactionBundle\Controller\TransactionController
    prefix:   /commercant

employeConsultation:
    type:     rest
    resource: EmployeBundle\Controller\ConsultationController
    prefix:   /employe/consultation

employeOpposition:
    type:     rest
    resource: EmployeBundle\Controller\OppositionController
    prefix:   /employe

employeProfile:
    type:     rest
    resource: EmployeBundle\Controller\ProfileController
    prefix:   /employe