security:
    encoders:
        AuthBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        auth_token_user_provider:
            id: auth_token_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: auth_token_authenticator
            provider: auth_token_user_provider
            anonymous: ~

    access_control:
        - { path: ^/auth/users/add, role: ROLE_EMPLOYE }
#        - { path: ^/employeur, role: ROLE_EMPLOYEUR }
#        - { path: ^/commercant, role: ROLE_COMMERCANT }
