TransactionBundle\Entity\VerifTransaction:
   properties:
        numeroCarte:
            - NotBlank:
                message: 'Le numero de la carte ne doit pas être vide'
        montant:
            - NotBlank:
                message: 'Le montant ne doit pas être vide'
            - Type:
                type: float
                message: 'Le montant doit être un chiffre'
            - LessThan:
                value: 100
                message: 'Le montant ne peut pas dépasser 100 euros'
            - GreaterThan:
                value: 1
                message: 'Le montant doit être supérieur à 1 euro'
        pin:
            - NotBlank:
                message: 'Le pin ne doit pas être vide'
            - Type:
                type: string
                message: 'Veuillez entrer un pin correct'
            - Length:
                exactMessage: 'Le pin doit comporter 4 chiffres'
                minMessage: 'Le pin doit comporter 4 chiffres'
                maxMessage: 'Le pin doit comporter 4 chiffres'
                min: 4
                max: 4