TransactionBundle\Entity\Transaction:
    exclusion_policy: none
    properties:
        id:
            groups: ['transactions']
        date:
            groups: ['transactions']
        montant:
            groups: ['transactions']
#        carte:
#            groups: ['transaction']
#        lecteur:
#            groups: ['transaction']
