<?php

namespace CommercantBundle\Repository;

/**
 * CommercantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommercantRepository extends \Doctrine\ORM\EntityRepository {
}
