<?php

namespace CommercantBundle\Repository;

/**
 * LecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LecteurRepository extends \Doctrine\ORM\EntityRepository
{
}
