EmployeBundle\Entity\Employe:
    exclusion_policy: none
    properties:
        id:
            groups: ['user', 'transaction']
        nom:
            groups: ['user', 'transaction']
        prenom:
            groups: ['user', 'transaction']
        dateNaissance:
            groups: ['user']
        numTel:
            groups: ['user']
        civilite:
            groups: ['user']
        photo:
            groups: ['user']
        carte:
            groups: ['user']
