EmployeBundle\Entity\Carte:
    exclusion_policy: none
    properties:
        id:
            groups: ['user', 'transaction']
        numero:
            groups: ['user', 'transaction']
        solde:
            groups: ['user', 'transaction']
        opposed:
            groups: ['user', 'transaction']
        categorie:
            groups: ['user', 'transaction']
        employe:
            groups: ['transaction']
