<?php

namespace AuthBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {
    public function findOneByEmailOrLogin($label){
        $user = $this->findOneByLogin($label);
        if (!$user) {
            $user = $this->findOneByEmail($label);
        }
        return $user;
    }
}
