EmployeurBundle\Entity\Employeur:
    exclusion_policy: none
    properties:
        id:
            groups: ['user']
        libelle:
            groups: ['user']
        nom:
            groups: ['user']
        prenom:
            groups: ['user']
        adresse:
            groups: ['user']
        siret:
            groups: ['user']
        numTel:
            groups: ['user']
        civilite:
            groups: ['user']
        photo:
            groups: ['user']
