CommercantBundle\Entity\Commercant:
    exclusion_policy: none
    properties:
        id:
            groups: ['user', 'transaction']
        libelle:
            groups: ['user', 'transaction']
        nom:
            groups: ['user']
        iban:
            groups: ['user']
        prenom:
            groups: ['user']
        adresse:
            groups: ['user']
        siret:
            groups: ['user']
        numTel:
            groups: ['user']
        civilite:
            groups: ['user']
        photo:
            groups: ['user']
