EmployeBundle\Entity\Employe:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [numTel]
            message: 'Ce numéro de téléphone est déja utilisé'
    properties:
        nom:
            - NotBlank:
                message: 'Le champs nom ne doit pas être vide'
        prenom:
            - NotBlank:
                message: 'Le champs prenom ne doit pas être vide'
        numTel:
            - NotBlank:
                message: 'Le champs numéro de téléphone ne doit pas être vide'
            - Length:
                minMessage: 'Le format du numéro de téléphone est invalide'
                maxMessage: 'Le format du numéro de téléphone est invalide'
                min: 10
                max: 15
        password:
            - NotBlank:
                message: Le champs mot de passe ne doit pas être vide
            - Type:
                type: string
                message: Veuillez entrer un mot de passe correct
            - Length:
                min: 5
                max: 25
        civilite:
            - NotBlank:
                message: 'Le champs civilite ne doit pas être vide'
            - Choice:
                choices: [Mr., Mme., Mlle.]
                message: 'Veuillez choisir une civilite correcte'
                strict: true